const quizData={math:[],science:[],gk:[],english:[],urdu:[],islamiat:[],computer:[]};
function q(Q,O,A,D,UQ,UO){return{question:Q,options:O,answer:A,diculty:D,urduQuestion:UQ||'',urduOptions:UO||[]};}
function r(a,b){return Math.floor(Math.random()*(b-a+1))+a;}
function s(a){let x=a.slice();for(let i=x.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]];}return x;}

for(let i=0;i<500;i++){
  let d=i<200?'easy':i<350?'medium':'hard';
  let type=i%12;
  if(type<3){let a=r(1,50),b=r(1,50),ans=a+b;quizData.math.push(q(`${a} + ${b} = ?`,s([ans,a+b+1,a+b-1,a+b+2].map(String)),String(ans),d,`${a} aur ${b} ko jama karein?`,[]));}
  else if(type<5){let a=r(10,100),b=r(1,50),ans=a-b;quizData.math.push(q(`${a} - ${b} = ?`,s([ans,a-b+1,a-b-1,a-b+2].map(String)),String(ans),d,`${a} mein se ${b} ghataein?`,[]));}
  else if(type<7){let a=r(2,20),b=r(2,20),ans=a*b;quizData.math.push(q(`${a} x ${b} = ?`,s([ans,a*b+1,a*b-1,a*b+a].map(String)),String(ans),d,`${a} zarab ${b} barabar?`,[]));}
  else if(type<9){let b=r(2,15),ans=r(2,15),a=b*ans;quizData.math.push(q(`${a} / ${b} = ?`,s([ans,ans+1,ans-1,ans+2].map(String)),String(ans),d,`${a} taqseem ${b} barabar?`,[]));}
  else if(type<10){let a=r(1,100),pct=r(10,90),ans=Math.round(a*pct/100);quizData.math.push(q(`${pct}% of ${a} = ?`,s([ans,ans+1,ans-1,ans+2].map(String)),String(ans),d,`${a} ka ${pct} feesad?`,[]));}
  else if(type<11){let a=r(2,20);quizData.math.push(q(`Square of ${a} = ?`,s([a*a,a*a+1,a*a-1,a*a+a].map(String)),String(a*a),d,`${a} ka murabba?`,[]));}
  else{let nums=['I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII','XIII','XIV','XV','XVI','XVII','XVIII','XIX','XX'];let n=r(1,20);quizData.math.push(q(`What is ${n} in Roman numerals?`,s([nums[n-1],nums[n],nums[n-2]||'I',nums[n+1]||'XX']),nums[n-1],d,`${n} ko Roman numeral mein likhein?`,[]));}
}

const sci=[
['What is H2O?',['Water','Carbon dioxide','Oxygen','Salt'],'Water','easy','H2O kya hai?',['Pani','Carbon dioxide','Oxygen','Namak']],
['Which planet is red?',['Mars','Venus','Jupiter','Saturn'],'Mars','easy','Kaunsa sayyara surkh hai?',['Mars','Venus','Jupiter','Saturn']],
['Plants absorb?',['Carbon dioxide','Oxygen','Nitrogen','Hydrogen'],'Carbon dioxide','easy','Pauday soondhte hain?',['Carbon dioxide','Oxygen','Nitrogen','Hydrogen']],
['Hardest natural substance?',['Diamond','Gold','Iron','Quartz'],'Diamond','easy','Sab se sakht fitri cheez?',['Heera','Sona','Loha','Quartz']],
['Adult human bones?',['206','208','210','200'],'206','medium','Baligh insaan ki haddiyan?',['206','208','210','200']],
['Speed of light?',['300,000 km/s','150,000 km/s','400,000 km/s','250,000 km/s'],'300,000 km/s','hard','Roshni ki raftar?',['300,000 km/s','150,000 km/s','400,000 km/s','250,000 km/s']],
['Blood pumping organ?',['Heart','Brain','Liver','Lungs'],'Heart','easy','Khoon pump karne wala azaa?',['Dil','Dimagh','Jigar','Phephre']],
['Bees collect?',['Nectar','Pollen','Water','Seeds'],'Nectar','easy','Shehad ki makkhiyan jama karti hain?',['Nectar','Pollen','Pani','Beej']],
['Most abundant gas in air?',['Nitrogen','Oxygen','CO2','Hydrogen'],'Nitrogen','medium','Hawa mein sab se zyada gas?',['Nitrogen','Oxygen','CO2','Hydrogen']],
['Photosynthesis happens in?',['Leaves','Roots','Stem','Flowers'],'Leaves','easy','Photosynthesis kahan hoti hai?',['Pattay','Jarren','Dantha','Phool']],
['Center of atom?',['Nucleus','Electron','Proton','Neutron'],'Nucleus','medium','Atom ka markaz?',['Nucleus','Electron','Proton','Neutron']],
['Largest planet?',['Jupiter','Saturn','Neptune','Uranus'],'Jupiter','easy','Sab se bara sayyara?',['Jupiter','Saturn','Neptune','Uranus']],
['Sun provides?',['Solar energy','Wind','Hydro','Geothermal'],'Solar energy','easy','Sooraj faraham karta hai?',['Solar energy','Hawa','Pani','Geothermal']],
['Red blood cells carry?',['Oxygen','Germs','Food','Waste'],'Oxygen','medium','Surokh khoon ke khalye le jate hain?',['Oxygen','Jaraseem','Khana','Fuzla']],
['Ship of the Desert?',['Camel','Horse','Elephant','Donkey'],'Camel','easy','Sehra ki kashti?',['Oont','Ghora','Hathi','Gadha']],
['Plant-eating animals?',['Herbivores','Carnivores','Omnivores','Scavengers'],'Herbivores','easy','Pauday khane wale janwar?',['Herbivores','Carnivores','Omnivores','Scavengers']],
['Liquid metal at room temp?',['Mercury','Iron','Gold','Silver'],'Mercury','medium','Kamre ke darja hararat par maeey dhaat?',['Para','Loha','Sona','Chandi']],
['Main gas in Sun?',['Hydrogen','Helium','Oxygen','Nitrogen'],'Hydrogen','hard','Sooraj mein mukhiya gas?',['Hydrogen','Helium','Oxygen','Nitrogen']],
['Keeps us on ground?',['Gravity','Magnetism','Friction','Tension'],'Gravity','easy','Hamein zameen par rakhta hai?',['Gravitational force','Magnetism','Friction','Tension']],
['Caterpillar to butterfly?',['Metamorphosis','Photosynthesis','Evolution','Germination'],'Metamorphosis','medium','Caterpillar se titli?',['Tabdeeli','Photosynthesis','Evolution','Ankuran']],
['Universal blood donor?',['O negative','AB positive','A positive','B negative'],'O negative','hard','Universal khoon denay wala?',['O negative','AB positive','A positive','B negative']],
['Cell part with DNA?',['Nucleus','Cytoplasm','Membrane','Mitochondria'],'Nucleus','medium','DNA wala khalye ka hissa?',['Nucleus','Cytoplasm','Jhilli','Mitochondria']],
['Vitamin from sunlight?',['Vitamin D','A','C','B'],'Vitamin D','medium','Dhoop se milne wala vitamin?',['Vitamin D','A','C','B']],
['Study of living things?',['Biology','Chemistry','Physics','Geology'],'Biology','easy','Zinda cheezon ki tadrees?',['Biology','Chemistry','Physics','Geology']],
['Planet with most moons?',['Saturn','Jupiter','Uranus','Neptune'],'Saturn','hard','Sab se zyada chaand wala sayyara?',['Saturn','Jupiter','Uranus','Neptune']],
['Main component of natural gas?',['Methane','Propane','Butane','Ethane'],'Methane','hard','Qudrati gas ka mukhiya juz?',['Methane','Propane','Butane','Ethane']],
['Blood filtering organ?',['Kidneys','Heart','Liver','Lungs'],'Kidneys','medium','Khoon saaf karne wala azaa?',['Gurday','Dil','Jigar','Phephre']],
['Ocean tides caused by?',['Moon gravity','Sun heat','Wind','Earth rotation'],'Moon gravity','medium','Samandar ki madd-jaz kis se ati hain?',['Chaand ki kashish','Sooraj ki garmi','Hawa','Zameen ka chakkar']],
['Flightless bird?',['Penguin','Eagle','Sparrow','Crow'],'Penguin','easy','Be-parwaz parinda?',['Penguin','Eagle','Chirya','Kauwa']],
['Chemical symbol for gold?',['Au','Ag','Fe','Cu'],'Au','medium','Sona ka chemical nishaan?',['Au','Ag','Fe','Cu']],
['Adult human teeth?',['32','28','30','34'],'32','easy','Baligh insaan ke daant?',['32','28','30','34']],
['Largest human organ?',['Skin','Liver','Heart','Brain'],'Skin','medium','Insaan ka sab se bara azaa?',['Jild','Jigar','Dil','Dimagh']],
['Flying dinosaur?',['Pterodactyl','T-Rex','Stegosaurus','Triceratops'],'Pterodactyl','easy','Parwaz karne wala dinosaur?',['Pterodactyl','T-Rex','Stegosaurus','Triceratops']],
['Top layer of Earth?',['Crust','Mantle','Core','Surface'],'Crust','easy','Zameen ki sab se upar wali teh?',['Crust','Mantle','Markaz','Satah']],
['Gas in floating balloons?',['Helium','Hydrogen','Oxygen','Nitrogen'],'Helium','easy','Urtay huay gubbaron mein gas?',['Helium','Hydrogen','Oxygen','Nitrogen']],
['Water to vapor?',['Evaporation','Condensation','Precipitation','Collection'],'Evaporation','easy','Pani se bhaap?',['Bukhari','Tasfiya','Barasna','Jama karna']],
['Largest animal brain?',['Sperm whale','Elephant','Human','Dolphin'],'Sperm whale','hard','Sab se bara janwari dimagh?',['Sperm whale','Hathi','Insaan','Dolphin']],
['Smallest unit of life?',['Cell','Atom','Molecule','Tissue'],'Cell','easy','Zindagi ka sab se chota unit?',['Khalya','Atom','Molecule','Tissue']],
['Closest planet to Sun?',['Mercury','Venus','Earth','Mars'],'Mercury','easy','Sooraj ke sab se qareeb sayyara?',['Mercury','Venus','Zameen','Mars']],
['Magnets attract?',['Iron','Plastic','Wood','Glass'],'Iron','easy','Maqsat kishe karte hain?',['Loha','Plastic','Lakdi','Sheesha']],
['Water vapor to liquid?',['Condensation','Evaporation','Precipitation','Transpiration'],'Condensation','medium','Bhaap se maeey?',['Tasfiya','Bukhari','Barasna','Transpiration']],
['Gas we breathe in?',['Oxygen','Carbon dioxide','Nitrogen','Helium'],'Oxygen','easy','Gas jo hum soondhte hain?',['Oxygen','Carbon dioxide','Nitrogen','Helium']],
['Brain of computer?',['CPU','Monitor','Keyboard','Mouse'],'CPU','easy','Computer ka dimagh?',['CPU','Monitor','Keyboard','Mouse']],
['Largest human organ?',['Skin','Liver','Heart','Brain'],'Skin','easy','Insaan ka sab se bara azaa?',['Jild','Jigar','Dil','Dimagh']],
['Chemical formula of salt?',['NaCl','H2O','CO2','KCl'],'NaCl','easy','Namak ka chemical formula?',['NaCl','Pani','Carbon dioxide','KCl']],
['Solar system center?',['Sun','Earth','Jupiter','Mars'],'Sun','easy','Nizam shamsi ka markaz?',['Sooraj','Zameen','Mushtari','Mareekh']],
['Heart beats per minute?',['72','50','90','100'],'72','medium','Dil ki dharakan har minute?',['72','50','90','100']],
['Unit of electric current?',['Ampere','Volt','Watt','Ohm'],'Ampere','medium','Barqee current ki unit?',['Ampere','Volt','Watt','Ohm']],
['Rainbow colors count?',['7','5','6','8'],'7','easy','Qous-o-qazah ke rang?',['7','5','6','8']],
['Freezing point of water?',['0 C','10 C','-5 C','5 C'],'0 C','easy','Pani ka jamna?',['0 C','10 C','-5 C','5 C']],
['Boiling point of water?',['100 C','90 C','110 C','80 C'],'100 C','easy','Pani ka ubalna?',['100 C','90 C','110 C','80 C']],
['Unit of force?',['Newton','Joule','Watt','Pascal'],'Newton','medium','Quwwat ki unit?',['Newton','Joule','Watt','Pascal']],
['What carries oxygen in blood?',['Red blood cells','White blood cells','Plasma','Platelets'],'Red blood cells','medium','Khoon mein oxygen kon le jata hai?',['Surkh khooni khuliyay','Safed khooni khuliyay','Plasma','Platelets']],
['Vitamin C source?',['Orange','Rice','Milk','Bread'],'Orange','easy','Vitamin C ka zariya?',['Kinoo','Chawal','Doodh','Roti']],
['Human body temperature?',['37 C','30 C','40 C','35 C'],'37 C','easy','Insaan ka jism ka temperature?',['37 C','30 C','40 C','35 C']],
['Which is a mammal?',['Whale','Shark','Crocodile','Eagle'],'Whale','medium','Kaunsa doodh pilane wala janwar hai?',['Whale','Shark','Mugarmach','Uqaab']],
['What do bees make?',['Honey','Milk','Wax','Silk'],'Honey','easy','Makhi kya banati hai?',['Shehad','Doodh','Moom','Resham']],
['Acid in lemon?',['Citric','Acetic','Lactic','Sulfuric'],'Citric','medium','Limoo mein kaunsa tezab?',['Citric','Acetic','Lactic','Sulfuric']],
['Study of plants?',['Botany','Zoology','Geology','Ecology'],'Botany','easy','Paudon ki science?',['Botany','Zoology','Geology','Ecology']],
['Study of animals?',['Zoology','Botany','Geology','Physics'],'Zoology','easy','Janwaron ki science?',['Zoology','Botany','Geology','Physics']],
['Study of stars?',['Astronomy','Astrology','Geology','Biology'],'Astronomy','easy','Sitaron ki science?',['Astronomy','Astrology','Geology','Biology']],
['Instrument to see stars?',['Telescope','Microscope','Periscope','Kaleidoscope'],'Telescope','easy','Sitaray dekhne ka aala?',['Telescope','Microscope','Periscope','Kaleidoscope']],
['Largest planet?',['Jupiter','Saturn','Neptune','Uranus'],'Jupiter','easy','Sab se bara sayyara?',['Jupiter','Saturn','Neptune','Uranus']],
['Closest planet to Sun?',['Mercury','Venus','Earth','Mars'],'Mercury','easy','Sooraj ke sab se qareeb sayyara?',['Mercury','Venus','Earth','Mars']],
['Which gas do plants release?',['Oxygen','Carbon dioxide','Nitrogen','Hydrogen'],'Oxygen','easy','Pauday konsi gas chhorte hain?',['Oxygen','Carbon dioxide','Nitrogen','Hydrogen']],
['What pulls objects toward Earth?',['Gravity','Magnetism','Friction','Electricity'],'Gravity','easy','Cheezon ko Zameen ki taraf khainchta hai?',['Gravity','Magnetism','Friction','Electricity']],
['What is the center of an atom?',['Nucleus','Electron','Proton','Neutron'],'Nucleus','medium','Atom ka markaz?',['Nucleus','Electron','Proton','Neutron']],
['Which bird cannot fly?',['Ostrich','Eagle','Sparrow','Crow'],'Ostrich','easy','Kaunsa parr nahin ur sakta?',['Ostrich','Eagle','Sparrow','Crow']],
['Earth has how many moons?',['1','2','0','3'],'1','easy','Zameen ke kitne chaand hain?',['1','2','0','3']],
['Moon has how many moons?',['0','1','2','3'],'0','easy','Chaand ke kitne chaand hain?',['0','1','2','3']],
['What protects Earth from UV rays?',['Ozone layer','Atmosphere','Magnetic field','Clouds'],'Ozone layer','medium','Zameen ko UV rays se kon bachata hai?',['Ozone layer','Atmosphere','Magnetic field','Clouds']],
['Process of water vapor rising?',['Evaporation','Condensation','Precipitation','Transpiration'],'Evaporation','medium','Pani ke bhaap ka oopar uthna?',['Evaporation','Condensation','Precipitation','Transpiration']],
['Gas used in fire extinguishers?',['Carbon dioxide','Oxygen','Nitrogen','Helium'],'Carbon dioxide','easy','Aag bujhane wala gas?',['Carbon dioxide','Oxygen','Nitrogen','Helium']],
['Chemical symbol for gold?',['Au','Ag','Fe','Cu'],'Au','medium','Sona ka chemical nishan?',['Au','Ag','Fe','Cu']],
['Chemical symbol for silver?',['Ag','Au','Fe','Cu'],'Ag','medium','Chandi ka chemical nishan?',['Ag','Au','Fe','Cu']],
['Chemical symbol for iron?',['Fe','Au','Ag','Cu'],'Fe','medium','Loha ka chemical nishan?',['Fe','Au','Ag','Cu']],
['Chemical symbol for copper?',['Cu','Au','Ag','Fe'],'Cu','medium','Tamba ka chemical nishan?',['Cu','Au','Ag','Fe']],
['Chemical symbol for oxygen?',['O','C','H','N'],'O','easy','Oxygen ka chemical nishan?',['O','C','H','N']],
['Chemical symbol for carbon?',['C','O','H','N'],'C','easy','Carbon ka chemical nishan?',['C','O','H','N']],
['Chemical symbol for hydrogen?',['H','O','C','N'],'H','easy','Hydrogen ka chemical nishan?',['H','O','C','N']],
['Chemical symbol for nitrogen?',['N','O','C','H'],'N','easy','Nitrogen ka chemical nishan?',['N','O','C','H']],
['Negative particle in atom?',['Electron','Proton','Neutron','Nucleus'],'Electron','hard','Atom ka manfi zarra?',['Electron','Proton','Neutron','Nucleus']],
['Positive particle in atom?',['Proton','Electron','Neutron','Nucleus'],'Proton','hard','Atom ka masbat zarra?',['Proton','Electron','Neutron','Nucleus']],
['Neutral particle in atom?',['Neutron','Proton','Electron','Nucleus'],'Neutron','hard','Atom ka be-tar zarra?',['Neutron','Proton','Electron','Nucleus']],
['What do we call baby frogs?',['Tadpoles','Caterpillars','Larvae','Puppies'],'Tadpoles','easy','Mendak ke bachon ko kya kehte hain?',['Tadpoles','Caterpillars','Larvae','Puppies']],
['What do we call baby butterflies?',['Caterpillars','Tadpoles','Larvae','Puppies'],'Caterpillars','easy','Titli ke bachon ko kya kehte hain?',['Caterpillars','Tadpoles','Larvae','Puppies']],
['Largest land animal?',['Elephant','Giraffe','Hippopotamus','Rhino'],'Elephant','easy','Sab se bara zameeni janwar?',['Elephant','Giraffe','Hippopotamus','Rhino']]];
['Study of plants?',['Botany','Zoology','Geology','Ecology'],'Botany','easy','Paudon ki science?',['Botany','Zoology','Geology','Ecology']],
['Study of animals?',['Zoology','Botany','Geology','Physics'],'Zoology','easy','Janwaron ki science?',['Zoology','Botany','Geology','Physics']],
['Study of stars?',['Astronomy','Astrology','Geology','Biology'],'Astronomy','easy','Sitaron ki science?',['Astronomy','Astrology','Geology','Biology']],
['Instrument to see stars?',['Telescope','Microscope','Periscope','Kaleidoscope'],'Telescope','easy','Sitaray dekhne ka aala?',['Telescope','Microscope','Periscope','Kaleidoscope']],
['Largest planet?',['Jupiter','Saturn','Neptune','Uranus'],'Jupiter','easy','Sab se bara sayyara?',['Jupiter','Saturn','Neptune','Uranus']],
['Closest planet to Sun?',['Mercury','Venus','Earth','Mars'],'Mercury','easy','Sooraj ke sab se qareeb sayyara?',['Mercury','Venus','Earth','Mars']],
['Which gas do plants release?',['Oxygen','Carbon dioxide','Nitrogen','Hydrogen'],'Oxygen','easy','Pauday konsi gas chhorte hain?',['Oxygen','Carbon dioxide','Nitrogen','Hydrogen']],
['What pulls objects toward Earth?',['Gravity','Magnetism','Friction','Electricity'],'Gravity','easy','Cheezon ko Zameen ki taraf khainchta hai?',['Gravity','Magnetism','Friction','Electricity']],
['Largest human organ?',['Skin','Liver','Heart','Brain'],'Skin','easy','Insaan ka sab se bara azaa?',['Skin','Liver','Heart','Brain']],
['Chemical formula of salt?',['NaCl','H2O','CO2','KCl'],'NaCl','easy','Namak ka chemical formula?',['NaCl','H2O','CO2','KCl']],
['Solar system center?',['Sun','Earth','Jupiter','Mars'],'Sun','easy','Nizam shamsi ka markaz?',['Sun','Earth','Jupiter','Mars']],
['Heart beats per minute?',['72','50','90','100'],'72','medium','Dil ki dharakan har minute?',['72','50','90','100']],
['Unit of electric current?',['Ampere','Volt','Watt','Ohm'],'Ampere','medium','Barqee current ki unit?',['Ampere','Volt','Watt','Ohm']],
['Rainbow colors count?',['7','5','6','8'],'7','easy','Qous-o-qazah ke rang?',['7','5','6','8']],
['Freezing point of water?',['0 C','10 C','-5 C','5 C'],'0 C','easy','Pani ka jamna?',['0 C','10 C','-5 C','5 C']],
['Boiling point of water?',['100 C','90 C','110 C','80 C'],'100 C','easy','Pani ka ubalna?',['100 C','90 C','110 C','80 C']],
['Unit of force?',['Newton','Joule','Watt','Pascal'],'Newton','medium','Quwwat ki unit?',['Newton','Joule','Watt','Pascal']],
['Smallest unit of life?',['Cell','Atom','Molecule','Tissue'],'Cell','medium','Zindagi ka chhota tukra?',['Cell','Atom','Molecule','Tissue']],
['Photosynthesis needs?',['Sunlight','Darkness','Cold','Rain'],'Sunlight','easy','Photosynthesis ke liye zaroori?',['Sunlight','Darkness','Cold','Rain']],
['Earth spins around?',['Sun','Moon','Mars','Venus'],'Sun','easy','Zameen kis ke gird ghoomti hai?',['Sun','Moon','Mars','Venus']],
sci.forEach(x=>quizData.science.push(q(x[0],s(x[1]),x[2],x[3],x[4],s(x[5]))));

const gk=[
['Capital of Pakistan?',['Islamabad','Karachi','Lahore','Peshawar'],'Islamabad','easy','Pakistan ka dar-ul-khilafa?',['Islamabad','Karachi','Lahore','Peshawar']],
['Largest continent?',['Asia','Africa','Europe','North America'],'Asia','easy','Sab se bara bar-e-azam?',['Asia','Africa','Europe','North America']],
['First PM of Pakistan?',['Liaquat Ali Khan','Jinnah','Ayub','Bhutto'],'Liaquat Ali Khan','medium','Pakistan ka pehla wazeer-e-azam?',['Liaquat Ali Khan','Jinnah','Ayub','Bhutto']],
['National language?',['Urdu','English','Punjabi','Sindhi'],'Urdu','easy','Qaumi zubaan?',['Urdu','Angrezi','Punjabi','Sindhi']],
['Longest river?',['Nile','Amazon','Yangtze','Mississippi'],'Nile','medium','Sab se lambi darya?',['Nile','Amazon','Yangtze','Mississippi']],
['National sport?',['Field Hockey','Cricket','Football','Kabaddi'],'Field Hockey','easy','Qaumi khel?',['Field Hockey','Cricket','Football','Kabaddi']],
['Telephone inventor?',['Alexander Graham Bell','Edison','Newton','Einstein'],'Alexander Graham Bell','medium','Telephone ijad karne wala?',['Alexander Graham Bell','Edison','Newton','Einstein']],
['Land of Rising Sun?',['Japan','China','Korea','Thailand'],'Japan','easy','Ufta sooraj ka mulk?',['Japan','China','Korea','Thailand']],
['Tallest mountain?',['Mount Everest','K2','Kangchenjunga','Lhotse'],'Mount Everest','easy','Sab se uncha pahar?',['Mount Everest','K2','Kangchenjunga','Lhotse']],
['Largest ocean?',['Pacific','Atlantic','Indian','Arctic'],'Pacific','easy','Sab se bara samandar?',['Pacific','Atlantic','Indian','Arctic']],
['National anthem writer?',['Hafeez Jalandhari','Iqbal','Faiz','Ghalib'],'Hafeez Jalandhari','medium','Qaumi tarana likhne wale?',['Hafeez Jalandhari','Iqbal','Faiz','Ghalib']],
['Currency of Pakistan?',['Pakistani Rupee','Dollar','Riyal','Taka'],'Pakistani Rupee','easy','Pakistan ka sikka?',['Pakistani Rupee','Dollar','Riyal','Taka']],
['Largest population?',['India','China','USA','Indonesia'],'India','easy','Sab se zyada abadi wala mulk?',['India','China','USA','Indonesia']],
['Father of Nation Pakistan?',['Muhammad Ali Jinnah','Liaquat','Iqbal','Bhutto'],'Muhammad Ali Jinnah','easy','Pakistan ka baba-e-qaum?',['Muhammad Ali Jinnah','Liaquat','Iqbal','Bhutto']],
['National flower?',['Jasmine','Rose','Sunflower','Lily'],'Jasmine','easy','Qaumi phool?',['Chambeli','Gulab','Surajmukhi','Sosan']],
['Desert in Pakistan?',['Thar','Sahara','Gobi','Kalahari'],'Thar','medium','Pakistan mein sehra?',['Thar','Sahara','Gobi','Kalahari']],
['Penicillin discoverer?',['Alexander Fleming','Pasteur','Curie','Darwin'],'Alexander Fleming','hard','Penicillin daryaft karne wala?',['Alexander Fleming','Pasteur','Curie','Darwin']],
['National animal?',['Markhor','Lion','Tiger','Elephant'],'Markhor','medium','Qaumi janwar?',['Markhor','Sher','Bagh','Hathi']],
['City of Lights?',['Karachi','Lahore','Islamabad','Peshawar'],'Karachi','easy','Roshniyon ka shehar?',['Karachi','Lahore','Islamabad','Peshawar']],
['Smallest country?',['Vatican City','Monaco','Malta','Luxembourg'],'Vatican City','medium','Sab se chota mulk?',['Vatican City','Monaco','Malta','Luxembourg']],
['Largest country by area?',['Russia','Canada','China','USA'],'Russia','easy','Sab se bara mulk (raqbe mein)?',['Russia','Canada','China','USA']],
['Deepest ocean point?',['Mariana Trench','Puerto Rico','Java','Philippine'],'Mariana Trench','hard','Samandar ka sab se gehra hissa?',['Mariana Trench','Puerto Rico','Java','Philippine']],
['Paper inventor country?',['China','Egypt','India','Greece'],'China','medium','Kaghaz ijad karne wala mulk?',['China','Egypt','India','Greece']],
['UN HQ?',['New York','Geneva','Paris','London'],'New York','medium','UN ka markazi daftar?',['New York','Geneva','Paris','London']],
['Nobel Prize country?',['Sweden','USA','UK','Germany'],'Sweden','medium','Nobel Prize dene wala mulk?',['Sweden','USA','UK','Germany']],
['National poet?',['Allama Iqbal','Faiz','Ghalib','Hafeez'],'Allama Iqbal','easy','Qaumi shair?',['Allama Iqbal','Faiz','Ghalib','Hafeez']],
['Indus River through?',['Pakistan','India','China','Afghanistan'],'Pakistan','easy','Darya-e-Sindh kis se guzarta hai?',['Pakistan','India','China','Afghanistan']],
['World Population Day?',['July 11','June 5','April 22','March 8'],'July 11','hard','World Population Day?',['11 July','5 June','22 April','8 March']],
['Longest wall?',['Great Wall of China','Berlin','Hadrian','Western'],'Great Wall of China','easy','Sab se lambi deewar?',['Great Wall of China','Berlin','Hadrian','Western']],
['Currency of Japan?',['Yen','Won','Dollar','Rupee'],'Yen','easy','Japan ka sikka?',['Yen','Won','Dollar','Rupee']],
['WWII end year?',['1945','1939','1941','1950'],'1945','medium','Dusri jang-e-azeem ka khatma?',['1945','1939','1941','1950']],
['Taj Mahal location?',['Agra','Delhi','Jaipur','Mumbai'],'Agra','easy','Taj Mahal kahan hai?',['Agra','Delhi','Jaipur','Mumbai']],
['Olympics origin?',['Greece','Italy','France','UK'],'Greece','medium','Olympics ki ibtedaa?',['Greece','Italy','France','UK']],
['Largest island?',['Greenland','Australia','Borneo','Madagascar'],'Greenland','medium','Sab se bara jazeera?',['Greenland','Australia','Borneo','Madagascar']],
['UK PM in WWII?',['Winston Churchill','Thatcher','Blair','Attlee'],'Winston Churchill','hard','UK ke PM dusri jang-e-azeem mein?',['Winston Churchill','Thatcher','Blair','Attlee']],
['Independence Day Pakistan?',['August 14','August 15','March 23','December 25'],'August 14','easy','Pakistan ka Youm-e-Azadi?',['14 August','15 August','23 March','25 December']],
['Capital of Turkey?',['Ankara','Istanbul','Izmir','Bursa'],'Ankara','medium','Turkey ka dar-ul-khilafa?',['Ankara','Istanbul','Izmir','Bursa']],
['Currency of Saudi Arabia?',['Riyal','Dinar','Dirham','Rupee'],'Riyal','easy','Saudi Arabia ka sikka?',['Riyal','Dinar','Dirham','Rupee']],
['FIFA 2022 host?',['Qatar','Russia','Brazil','Germany'],'Qatar','easy','FIFA 2022 mezbaan?',['Qatar','Russia','Brazil','Germany']],
['First man on moon?',['Neil Armstrong','Buzz Aldrin','Yuri Gagarin','Michael Collins'],'Neil Armstrong','medium','Chaand par pehla insaan?',['Neil Armstrong','Buzz Aldrin','Yuri Gagarin','Michael Collins']],
['Pakistan independence year?',['1947','1948','1950','1945'],'1947','easy','Pakistan ki azadi ka saal?',['1947','1948','1950','1945']],
['Microsoft founder?',['Bill Gates','Steve Jobs','Mark Zuckerberg','Elon Musk'],'Bill Gates','easy','Microsoft ke banane wale?',['Bill Gates','Steve Jobs','Mark Zuckerberg','Elon Musk']],
['Pakistan Day?',['March 23','August 14','September 6','December 25'],'March 23','easy','Pakistan Day?',['23 March','14 August','6 September','25 December']],
['Largest dam Pakistan?',['Tarbela','Mangla','Warsak','Kalabagh'],'Tarbela','medium','Pakistan ka sab se bara band?',['Tarbela','Mangla','Warsak','Kalabagh']],
['Country of K2?',['Pakistan','India','Nepal','China'],'Pakistan','medium','K2 kis mulk mein hai?',['Pakistan','India','Nepal','China']],
['Currency of UK?',['Pound Sterling','Euro','Dollar','Rupee'],'Pound Sterling','easy','UK ka sikka?',['Pound Sterling','Euro','Dollar','Rupee']],
['Year became republic?',['1956','1947','1958','1962'],'1956','hard','Pakistan jamhoori kab bana?',['1956','1947','1958','1962']]];
['Capital of Japan?',['Tokyo','Kyoto','Osaka','Nagoya'],'Tokyo','easy','Japan ka dar-ul-khilafa?',['Tokyo','Kyoto','Osaka','Nagoya']],
['Capital of China?',['Beijing','Shanghai','Guangzhou','Shenzhen'],'Beijing','easy','China ka dar-ul-khilafa?',['Beijing','Shanghai','Guangzhou','Shenzhen']],
['Capital of India?',['New Delhi','Mumbai','Kolkata','Chennai'],'New Delhi','easy','India ka dar-ul-khilafa?',['New Delhi','Mumbai','Kolkata','Chennai']],
['Capital of USA?',['Washington D.C.','New York','Los Angeles','Chicago'],'Washington D.C.','easy','USA ka dar-ul-khilafa?',['Washington D.C.','New York','Los Angeles','Chicago']],
['Capital of UK?',['London','Manchester','Birmingham','Liverpool'],'London','easy','UK ka dar-ul-khilafa?',['London','Manchester','Birmingham','Liverpool']],
gk.forEach(x=>quizData.gk.push(q(x[0],s(x[1]),x[2],x[3],x[4],s(x[5]))));

const eng=[
['Synonym of Happy?',['Joyful','Sad','Angry','Tired'],'Joyful','easy'],
['Opposite of Big?',['Small','Huge','Large','Giant'],'Small','easy'],
['Plural of Child?',['Children','Childs','Childes','Childrens'],'Children','easy'],
['Correct spelling?',['Beautiful','Beutiful','Beautifull','Beutifull'],'Beautiful','easy'],
['Past tense of Go?',['Went','Gone','Going','Goes'],'Went','easy'],
['Person who writes books?',['Author','Painter','Singer','Actor'],'Author','easy'],
['Synonym of Fast?',['Quick','Slow','Lazy','Late'],'Quick','easy'],
['Opposite of Hot?',['Cold','Warm','Boiling','Sunny'],'Cold','easy'],
['Which is a noun?',['Dog','Run','Quickly','Beautiful'],'Dog','medium'],
['Which is a verb?',['Jump','Happy','Blue','Table'],'Jump','medium'],
['Plural of Mouse?',['Mice','Mouses','Mices','Mousees'],'Mice','medium'],
['Correct spelling?',['Necessary','Neccessary','Necesary','Necessery'],'Necessary','medium'],
['Feminine of Lion?',['Lioness','Lion','Leopard','Tiger'],'Lioness','easy'],
['Place to keep books?',['Library','Kitchen','Garden','Hospital'],'Library','easy'],
['Opposite of Brave?',['Cowardly','Strong','Bold','Fearless'],'Cowardly','easy'],
['Which is an adjective?',['Red','Apple','Eat','Quickly'],'Red','medium'],
['Antonym of Wealthy?',['Poor','Rich','Prosperous','Lucky'],'Poor','easy'],
['He ___ to school.',['Goes','Go','Going','Gone'],'Goes','easy'],
['Which is a pronoun?',['He','Run','Happy','Tree'],'He','medium'],
['Meaning of Enormous?',['Very large','Small','Tiny','Weak'],'Very large','medium'],
['Homophone of Sea?',['See','Si','Saw','Say'],'See','medium'],
['I ___ my homework.',['Did','Do','Done','Does'],'Did','easy'],
['Synonym of Angry?',['Furious','Happy','Calm','Glad'],'Furious','medium'],
['Opposite of Always?',['Never','Sometimes','Often','Frequently'],'Never','easy'],
['Collective noun for cows?',['Herd','Flock','Pack','School'],'Herd','medium'],
['Which is a preposition?',['Under','Run','Blue','Jump'],'Under','medium'],
['Correct spelling?',['Accommodation','Acomodation','Accomodation','Acommodation'],'Accommodation','hard'],
['Past tense of Eat?',['Ate','Eated','Eaten','Eating'],'Ate','easy'],
['Synonym of Beautiful?',['Pretty','Ugly','Plain','Dull'],'Pretty','easy'],
['Opposite of Early?',['Late','Soon','Quick','First'],'Late','easy'],
['Group of lions?',['Pride','Herd','Pack','Flock'],'Pride','medium'],
['Which is an adverb?',['Quickly','Blue','Table','Run'],'Quickly','medium'],
['Correct spelling?',['Environment','Enviroment','Envirement','Environnment'],'Environment','medium'],
['Plural of Tooth?',['Teeth','Tooths','Toothes','Teethes'],'Teeth','easy'],
['She is ___ than her sister.',['Taller','Tall','More tall','Most tall'],'Taller','medium'],
['Antonym of Difficult?',['Easy','Hard','Tough','Complex'],'Easy','easy'],
['Person who flies a plane?',['Pilot','Driver','Sailor','Cook'],'Pilot','easy'],
['Which is a conjunction?',['And','Run','Beautiful','Quickly'],'And','medium'],
['Correct spelling?',['Occasion','Ocasion','Occassion','Ocassion'],'Occasion','hard'],
['Synonym of Begin?',['Start','End','Finish','Stop'],'Start','easy'],
['Opposite of Success?',['Failure','Win','Victory','Gain'],'Failure','easy'],
['___ apple a day...',['An','A','The','No'],'An','easy'],
['The cat ___ on the mat.',['Sat','Sit','Sitted','Siting'],'Sat','easy'],
['Collective noun for sheep?',['Flock','Herd','Pack','Pride'],'Flock','medium'],
['Synonym of Smart?',['Intelligent','Dull','Slow','Foolish'],'Intelligent','easy'],
['Antonym of Ancient?',['Modern','Old','Past','Historical'],'Modern','medium'],
['Correct spelling?',['Separate','Seperate','Seprate','Seperrate'],'Separate','medium'],
['Person who teaches?',['Teacher','Doctor','Engineer','Pilot'],'Teacher','easy'],
['Which is an interjection?',['Wow','Run','Blue','Quickly'],'Wow','medium'],
['Plural of Foot?',['Feet','Foots','Footes','Feets'],'Feet','easy']];
eng.forEach(x=>quizData.english.push(q(x[0],s(x[1]),x[2],x[3],x[4]||'',s(x[5]||[]))));

const isl=[
['First prophet in Islam?',['Adam','Muhammad','Noah','Abraham'],'Adam','easy'],
['Last prophet in Islam?',['Muhammad','Moses','Jesus','David'],'Muhammad','easy'],
['Holy book of Islam?',['Quran','Bible','Torah','Zabur'],'Quran','easy'],
['How many pillars of Islam?',['Five','Four','Six','Seven'],'Five','easy'],
['First pillar of Islam?',['Shahada','Salah','Zakat','Sawm'],'Shahada','easy'],
['Daily prayers in Islam?',['Salah','Zakat','Hajj','Sawm'],'Salah','easy'],
['Month of fasting?',['Ramadan','Shawwal','Muharram','Dhul Hijjah'],'Ramadan','easy'],
['Pilgrimage to Makkah?',['Hajj','Umrah','Zakat','Sawm'],'Hajj','easy'],
['Charity in Islam?',['Zakat','Sadaqah','Fitrah','Khums'],'Zakat','easy'],
['Birth city of Prophet Muhammad?',['Makkah','Madinah','Jerusalem','Taif'],'Makkah','easy'],
['Migration to Madinah called?',['Hijrah','Jihad','Sunnah','Sharia'],'Hijrah','medium'],
['Prophet received first revelation in?',['Cave Hira','Makkah','Madinah','Jerusalem'],'Cave Hira','medium'],
['Angel who brought revelation?',['Jibreel','Mikaeel','Israfeel','Azrael'],'Jibreel','easy'],
['Islamic New Year month?',['Muharram','Ramadan','Shawwal','Safar'],'Muharram','medium'],
['Night of Decree?',['Laylatul Qadr','Eid night','Friday','Arafah'],'Laylatul Qadr','medium'],
['Eid after Ramadan?',['Eid al-Fitr','Eid al-Adha','Ashura','Friday'],'Eid al-Fitr','easy'],
['Eid after Hajj?',['Eid al-Adha','Eid al-Fitr','Ashura','Milad'],'Eid al-Adha','easy'],
['Sacred month besides Ramadan?',['Dhul Hijjah','Shawwal','Safar','Rabi'],'Dhul Hijjah','medium'],
['Prophet Muhammad uncle?',['Abu Talib','Abu Bakr','Umar','Ali'],'Abu Talib','hard'],
['First caliph?',['Abu Bakr','Umar','Uthman','Ali'],'Abu Bakr','easy'],
['Second caliph?',['Umar','Abu Bakr','Uthman','Ali'],'Umar','easy'],
['Third caliph?',['Uthman','Abu Bakr','Umar','Ali'],'Uthman','easy'],
['Fourth caliph?',['Ali','Abu Bakr','Umar','Uthman'],'Ali','easy'],
['Wife of Prophet called Mother of Believers?',['Aisha','Khadija','Hafsa','Zainab'],'Aisha','hard'],
['Prophet first wife?',['Khadija','Aisha','Hafsa','Zainab'],'Khadija','easy'],
['Prophet daughter?',['Fatima','Aisha','Khadija','Maryam'],'Fatima','easy'],
['Prophet grandson?',['Husayn','Hasan','Ali','Abbas'],'Husayn','easy'],
['Battle of Badr year?',['2 AH','1 AH','3 AH','5 AH'],'2 AH','hard'],
['Prophet age when he died?',['63','60','65','70'],'63','medium'],
['Prophet age when he received revelation?',['40','30','35','45'],'40','easy'],
['Quran revealed over how many years?',['23','10','15','30'],'23','medium'],
['How many chapters in Quran?',['114','100','120','110'],'114','easy'],
['Longest chapter in Quran?',['Al-Baqarah','Al-Ikhlas','Al-Fatiha','Yasin'],'Al-Baqarah','medium'],
['Shortest chapter in Quran?',['Al-Kawthar','Al-Ikhlas','Al-Falaq','An-Nas'],'Al-Kawthar','medium'],
['First chapter of Quran?',['Al-Fatiha','Al-Baqarah','Yasin','Al-Ikhlas'],'Al-Fatiha','easy'],
['How many rakahs in Fajr?',['2','4','3','1'],'2','easy'],
['How many rakahs in Dhuhr?',['4','2','3','1'],'4','easy'],
['How many rakahs in Asr?',['4','2','3','1'],'4','easy'],
['How many rakahs in Maghrib?',['3','4','2','1'],'3','easy'],
['How many rakahs in Isha?',['4','3','2','1'],'4','easy'],
['Direction Muslims pray?',['Qibla','Makkah','Madinah','Jerusalem'],'Qibla','easy'],
['Islamic call to prayer?',['Adhan','Iqamah','Khutbah','Dua'],'Adhan','easy'],
['Leadership sermon on Friday?',['Khutbah','Adhan','Dua','Tilawat'],'Khutbah','easy'],
['Islamic ablution?',['Wudu','Ghusl','Tayammum','Zakat'],'Wudu','easy'],
['Full body wash ritual?',['Ghusl','Wudu','Tayammum','Sawm'],'Ghusl','medium'],
['Dry ablution with clean earth?',['Tayammum','Wudu','Ghusl','Zakat'],'Tayammum','hard'],
['Night journey of Prophet?',['Isra and Miraj','Hijrah','Badr','Uhud'],'Isra and Miraj','medium'],
['Prophet ascended to heavens from?',['Jerusalem','Makkah','Madinah','Taif'],'Jerusalem','medium'],
['Year of Sorrow?',['10th year of Prophethood','1st year','5th year','20th year'],'10th year of Prophethood','hard'],
['Uncle and wife died in Year of Sorrow?',['Abu Talib and Khadija','Hamza and Aisha','Abbas and Fatima','Umar and Hafsa'],'Abu Talib and Khadija','hard'],
['Battle where Prophet was injured?',['Uhud','Badr','Trench','Hunayn'],'Uhud','medium'],
['Battle with trench digging?',['Battle of Trench','Badr','Uhud','Hunayn'],'Battle of Trench','medium'],
['City Prophet migrated to?',['Madinah','Makkah','Jerusalem','Taif'],'Madinah','easy'],
['Prophet mosque in Madinah?',['Masjid an-Nabawi','Masjid al-Haram','Al-Aqsa','Quba'],'Masjid an-Nabawi','easy'],
['First mosque in Islam?',['Masjid Quba','Masjid an-Nabawi','Masjid al-Haram','Al-Aqsa'],'Masjid Quba','medium'],
['Sacred mosque in Makkah?',['Masjid al-Haram','Masjid an-Nabawi','Al-Aqsa','Quba'],'Masjid al-Haram','easy'],
['Black stone in Kaaba called?',['Hajar al-Aswad','Hajar al-Abyad','Rukn','Mizab'],'Hajar al-Aswad','medium'],
['Well of Zamzam located in?',['Makkah','Madinah','Jerusalem','Taif'],'Makkah','easy'],
['Prophet Muhammad father?',['Abdullah','Abu Talib','Abdul Muttalib','Hamza'],'Abdullah','medium'],
['Prophet Muhammad mother?',['Aminah','Khadija','Aisha','Fatima'],'Aminah','medium']];
isl.forEach(x=>quizData.islamiat.push(q(x[0],s(x[1]),x[2],x[3],x[4]||'',s(x[5]||[]))));

const cmp=[
['Brain of computer?',['CPU','Monitor','Keyboard','Mouse'],'CPU','easy'],
['Which is output device?',['Monitor','Keyboard','Mouse','Scanner'],'Monitor','easy'],
['Which is input device?',['Keyboard','Monitor','Printer','Speaker'],'Keyboard','easy'],
['Full form of RAM?',['Random Access Memory','Read Access Memory','Run Access Memory','Random Application Memory'],'Random Access Memory','easy'],
['Full form of ROM?',['Read Only Memory','Random Only Memory','Read Output Memory','Run Only Memory'],'Read Only Memory','easy'],
['What does CPU stand for?',['Central Processing Unit','Computer Processing Unit','Central Program Unit','Computer Program Unit'],'Central Processing Unit','easy'],
['Operating system by Microsoft?',['Windows','Linux','macOS','Android'],'Windows','easy'],
['Operating system by Apple?',['macOS','Windows','Linux','Android'],'macOS','easy'],
['Open source operating system?',['Linux','Windows','macOS','iOS'],'Linux','medium'],
['Spreadsheet software?',['Microsoft Excel','Microsoft Word','PowerPoint','Notepad'],'Microsoft Excel','easy'],
['Word processing software?',['Microsoft Word','Excel','PowerPoint','Paint'],'Microsoft Word','easy'],
['Presentation software?',['Microsoft PowerPoint','Word','Excel','Photoshop'],'Microsoft PowerPoint','easy'],
['Internet browser by Google?',['Google Chrome','Firefox','Safari','Edge'],'Google Chrome','easy'],
['Internet browser by Mozilla?',['Firefox','Chrome','Safari','Edge'],'Firefox','easy'],
['Search engine by Google?',['Google Search','Bing','Yahoo','DuckDuckGo'],'Google Search','easy'],
['Social media by Meta?',['Facebook','Twitter','Snapchat','TikTok'],'Facebook','easy'],
['Video platform by Google?',['YouTube','Vimeo','Dailymotion','Netflix'],'YouTube','easy'],
['Founder of Microsoft?',['Bill Gates','Steve Jobs','Mark Zuckerberg','Elon Musk'],'Bill Gates','easy'],
['Founder of Apple?',['Steve Jobs','Bill Gates','Mark Zuckerberg','Elon Musk'],'Steve Jobs','medium'],
['Founder of Facebook?',['Mark Zuckerberg','Bill Gates','Steve Jobs','Elon Musk'],'Mark Zuckerberg','medium'],
['Full form of URL?',['Uniform Resource Locator','Universal Resource Locator','Uniform Resource Link','Universal Resource Link'],'Uniform Resource Locator','medium'],
['Full form of HTTP?',['HyperText Transfer Protocol','HyperText Transport Protocol','HighText Transfer Protocol','HyperText Transfer Process'],'HyperText Transfer Protocol','medium'],
['Full form of WWW?',['World Wide Web','World Wide Website','Web World Wide','Wide World Web'],'World Wide Web','easy'],
['Full form of HTML?',['HyperText Markup Language','HyperText Makeup Language','HighText Markup Language','HyperText Markup Link'],'HyperText Markup Language','medium'],
['Full form of CSS?',['Cascading Style Sheets','Computer Style Sheets','Creative Style Sheets','Colorful Style Sheets'],'Cascading Style Sheets','medium'],
['Programming language for web pages?',['JavaScript','HTML','CSS','SQL'],'JavaScript','easy'],
['Language for database queries?',['SQL','HTML','CSS','Python'],'SQL','medium'],
['Language for Android apps?',['Java','Swift','C#','PHP'],'Java','medium'],
['Language for iOS apps?',['Swift','Java','C#','Python'],'Swift','medium'],
['Python is a?',['Programming language','Snake','Software','Browser'],'Programming language','easy'],
['What is a computer virus?',['Malicious software','Hardware problem','Operating system','Browser'],'Malicious software','easy'],
['Software that protects from viruses?',['Antivirus','Firewall','Browser','VPN'],'Antivirus','easy'],
['What does VPN stand for?',['Virtual Private Network','Virtual Public Network','Very Private Network','Virtual Protected Network'],'Virtual Private Network','medium'],
['Storage device?',['Hard Disk','Monitor','Keyboard','Mouse'],'Hard Disk','easy'],
['Portable storage device?',['USB Flash Drive','Monitor','Printer','Scanner'],'USB Flash Drive','easy'],
['Cloud storage by Google?',['Google Drive','OneDrive','iCloud','Dropbox'],'Google Drive','easy'],
['Cloud storage by Microsoft?',['OneDrive','Google Drive','iCloud','Dropbox'],'OneDrive','easy'],
['Email service by Google?',['Gmail','Yahoo Mail','Outlook','Hotmail'],'Gmail','easy'],
['Email service by Microsoft?',['Outlook','Gmail','Yahoo Mail','AOL'],'Outlook','easy'],
['What is a pixel?',['Tiny dot on screen','Type of file','Computer part','Software'],'Tiny dot on screen','medium'],
['What does DPI stand for?',['Dots Per Inch','Digital Per Inch','Display Per Inch','Dots Per Image'],'Dots Per Inch','hard'],
['Keyboard shortcut for copy?',['Ctrl+C','Ctrl+V','Ctrl+X','Ctrl+Z'],'Ctrl+C','easy'],
['Keyboard shortcut for paste?',['Ctrl+V','Ctrl+C','Ctrl+X','Ctrl+Z'],'Ctrl+V','easy'],
['Keyboard shortcut for undo?',['Ctrl+Z','Ctrl+C','Ctrl+V','Ctrl+Y'],'Ctrl+Z','easy'],
['Keyboard shortcut for save?',['Ctrl+S','Ctrl+P','Ctrl+O','Ctrl+N'],'Ctrl+S','easy'],
['Keyboard shortcut for print?',['Ctrl+P','Ctrl+S','Ctrl+O','Ctrl+N'],'Ctrl+P','easy'],
['What is a file extension?',['Letters after dot in filename','Part of keyboard','Type of virus','Computer brand'],'Letters after dot in filename','medium'],
['Extension for text document?',['.txt','.doc','.pdf','.jpg'],'.txt','easy'],
['Extension for image?',['.jpg','.txt','.doc','.mp3'],'.jpg','easy'],
['Extension for audio?',['.mp3','.jpg','.txt','.doc'],'.mp3','easy'],
['Extension for video?',['.mp4','.jpg','.txt','.doc'],'.mp4','easy'],
['Extension for web page?',['.html','.txt','.doc','.jpg'],'.html','easy'],
['Extension for Word document?',['.docx','.txt','.pdf','.jpg'],'.docx','easy'],
['Extension for PDF?',['.pdf','.doc','.txt','.jpg'],'.pdf','easy'],
['Extension for Excel?',['.xlsx','.doc','.txt','.jpg'],'.xlsx','easy'],
['Extension for PowerPoint?',['.pptx','.doc','.txt','.jpg'],'.pptx','easy'],
['What is a computer network?',['Connected computers','Single computer','Type of software','Computer brand'],'Connected computers','easy'],
['What is the Internet?',['Global network of networks','Single network','Type of software','Computer part'],'Global network of networks','easy'],
['What is Wi-Fi?',['Wireless network connection','Wired network','Bluetooth','Cable'],'Wireless network connection','easy'],
['What is Bluetooth?',['Wireless short-range connection','Wi-Fi','Cable','Ethernet'],'Wireless short-range connection','easy'],
['What is a firewall?',['Network security system','Type of virus','Browser','Operating system'],'Network security system','medium'],
['What is a server?',['Computer that provides services','Type of virus','Browser','Monitor'],'Computer that provides services','easy'],
['What is a client?',['Computer that requests services','Server','Monitor','Printer'],'Computer that requests services','easy'],
['What is a domain name?',['Website address name','Email address','File name','Computer name'],'Website address name','medium'],
['What is an IP address?',['Unique network identifier','Email address','Website name','File location'],'Unique network identifier','medium'],
['Binary digit called?',['Bit','Byte','Pixel','Word'],'Bit','easy'],
['8 bits make?',['1 Byte','1 Pixel','1 Word','1 KB'],'1 Byte','easy'],
['1024 bytes make?',['1 Kilobyte','1 Megabyte','1 Gigabyte','1 Terabyte'],'1 Kilobyte','easy'],
['1024 KB make?',['1 Megabyte','1 Gigabyte','1 Terabyte','1 Byte'],'1 Megabyte','easy'],
['1024 MB make?',['1 Gigabyte','1 Terabyte','1 Kilobyte','1 Byte'],'1 Gigabyte','easy'],
['What is an algorithm?',['Step-by-step instructions','Type of virus','Computer brand','Programming language'],'Step-by-step instructions','medium'],
['What is a bug?',['Error in program','Type of virus','Computer part','Antivirus'],'Error in program','easy'],
['Process of fixing errors?',['Debugging','Programming','Coding','Hacking'],'Debugging','easy'],
['What is coding?',['Writing instructions for computer','Drawing pictures','Playing games','Browsing internet'],'Writing instructions for computer','easy'],
['What is AI?',['Artificial Intelligence','Automatic Intelligence','Advanced Internet','Applied Intelligence'],'Artificial Intelligence','easy'],
['What is machine learning?',['Computer learns from data','Machine repairs itself','Computer programming','Hardware upgrade'],'Computer learns from data','hard'],
['What is a robot?',['Machine that can be programmed','Living thing','Type of software','Virus'],'Machine that can be programmed','easy'],
['Full form of PDF?',['Portable Document Format','Personal Document Format','Portable Data File','Printed Document Format'],'Portable Document Format','easy'],
['What is a screenshot?',['Image of computer screen','Type of virus','Computer part','File format'],'Image of computer screen','easy'],
['What is a password?',['Secret code for access','Username','Email address','Website name'],'Secret code for access','easy'],
['What is two-factor authentication?',['Two-step verification','Two passwords','Two usernames','Two emails'],'Two-step verification','hard'],
['What is phishing?',['Fake emails to steal data','Fishing game','Type of virus','Browser'],'Fake emails to steal data','hard'],
['What is spam?',['Unwanted emails','Ham','Virus','Browser'],'Unwanted emails','easy'],
['What is a database?',['Organized collection of data','Type of virus','Computer part','Browser'],'Organized collection of data','medium'],
['What is a spreadsheet?',['Table of data','Word document','Presentation','Image'],'Table of data','easy'],
['What is a cursor?',['Blinking line showing position','Mouse arrow','Keyboard key','File icon'],'Blinking line showing position','easy'],
['What is a desktop?',['Main screen area','Type of computer','Folder','File'],'Main screen area','easy'],
['What is a folder?',['Container for files','Type of virus','Browser','Monitor'],'Container for files','easy'],
['What is a file?',['Collection of data','Folder','Virus','Monitor'],'Collection of data','easy'],
['What is copy-paste?',['Duplicate and place data','Delete data','Move data','Rename data'],'Duplicate and place data','easy'],
['What is drag and drop?',['Move with mouse click and hold','Type of virus','Keyboard shortcut','File format'],'Move with mouse click and hold','easy'],
['What is a hyperlink?',['Clickable link to another page','Image','Video','Folder'],'Clickable link to another page','easy'],
['What is download?',['Copy from internet to computer','Delete file','Upload file','Print file'],'Copy from internet to computer','easy'],
['What is upload?',['Send file to internet','Download file','Delete file','Print file'],'Send file to internet','easy'],
['What is a zip file?',['Compressed file','Image file','Video file','Audio file'],'Compressed file','medium'],
['What is a QR code?',['Quick Response code','Question Response','Query Reader','Quick Reader'],'Quick Response code','medium'],
['What does USB stand for?',['Universal Serial Bus','Universal System Bus','Universal Storage Bus','Universal Software Bus'],'Universal Serial Bus','medium']];
cmp.forEach(x=>quizData.computer.push(q(x[0],s(x[1]),x[2],x[3],x[4]||'',s(x[5]||[]))));

const urdu=[
['اردو کا سب سے بڑا شاعر کون ہے؟',['علامہ اقبال','میر تقی میر','غالب','فیض احمد فیض'],'علامہ اقبال','easy'],
['اردو زبان کس رسم الخط میں لکھی جاتی ہے؟',['نستعلیق','ناخن','رومن','دیوانا'],'نستعلیق','easy'],
['پاکستان کا قومی زبان کون سی ہے؟',['اردو','انگریزی','پنجابی','سندھی'],'اردو','easy'],
['علامہ اقبال کا مشہور نظم "سارے جہاں سے اچھا" کس کے نام ہے؟',['طفل مکتب','شیخ','جواں','بزرگ'],'طفل مکتب','medium'],
['اردو کے پہلے شاعر کون مانے جاتے ہیں؟',['امیر خسرو','غالب','میر','سودا'],'امیر خسرو','medium'],
['اردو کا لفظ "شکر" کا مطلب کیا ہے؟',['Sugar','Salt','Spice','Honey'],'Sugar','easy'],
['اردو میں "کتاب" کا جمع کیا ہے؟',['کتب','کتوب','کتابیں','کتبہ'],'کتب','medium'],
['اردو میں "پانی" کا مطلب کیا ہے؟',['Water','Fire','Air','Earth'],'Water','easy'],
['اردو میں "آسمان" کا مطلب ہے؟',['Sky','Star','Moon','Sun'],'Sky','easy'],
['اردو میں "زمین" کا مطلب ہے؟',['Earth','Water','Fire','Air'],'Earth','easy'],
['اردو میں "شمس" کا مطلب ہے؟',['Sun','Moon','Star','Light'],'Sun','easy'],
['اردو میں "قمر" کا مطلب ہے؟',['Moon','Sun','Star','Night'],'Moon','easy'],
['اردو میں "ستارہ" کا مطلب ہے؟',['Star','Moon','Sun','Sky'],'Star','easy'],
['اردو میں "پھول" کا جمع کیا ہے؟',['پھول','پھولوں','پھولی','پھل'],'پھول','easy'],
['اردو میں "درخت" کا جمع کیا ہے؟',['درخت','درختوں','درختی','درختیں'],'درخت','easy'],
['اردو میں "لڑکا" کا جمع کیا ہے؟',['لڑکے','لڑکوں','لڑکا','لڑکی'],'لڑکے','easy'],
['اردو میں "لڑکی" کا جمع کیا ہے؟',['لڑکیاں','لڑکیوں','لڑکی','لڑکے'],'لڑکیاں','easy'],
['اردو میں "خوبصورت" کا مطلب ہے؟',['Beautiful','Ugly','Bad','Good'],'Beautiful','easy'],
['اردو میں "برا" کا مطلب ہے؟',['Bad','Good','Beautiful','Big'],'Bad','easy'],
['اردو میں "اچھا" کا مطلب ہے؟',['Good','Bad','Beautiful','Small'],'Good','easy'],
['اردو میں "بڑا" کا مطلب ہے؟',['Big','Small','Good','Bad'],'Big','easy'],
['اردو میں "چھوٹا" کا مطلب ہے؟',['Small','Big','Good','Bad'],'Small','easy'],
['اردو میں "لمبا" کا مطلب ہے؟',['Tall','Short','Fat','Thin'],'Tall','easy'],
['اردو میں "گھٹیا" کا مطلب ہے؟',['Short','Tall','Fat','Thin'],'Short','easy'],
['اردو میں "موٹا" کا مطلب ہے؟',['Fat','Thin','Tall','Short'],'Fat','easy'],
['اردو میں "پتلا" کا مطلب ہے؟',['Thin','Fat','Tall','Short'],'Thin','easy'],
['اردو میں "تازہ" کا مطلب ہے؟',['Fresh','Stale','Old','New'],'Fresh','easy'],
['اردو میں "پurانا" کا مطلب ہے؟',['Old','New','Fresh','Young'],'Old','easy'],
['اردو میں "نیا" کا مطلب ہے؟',['New','Old','Fresh','Young'],'New','easy'],
['اردو میں "تک" کا مطلب ہے؟',['Fast','Slow','Quick','Rapid'],'Fast','easy'],
['اردو میں "دھیما" کا مطلب ہے؟',['Slow','Fast','Quick','Rapid'],'Slow','easy'],
['اردو میں "گرم" کا مطلب ہے؟',['Hot','Cold','Warm','Cool'],'Hot','easy'],
['اردو میں "ٹھنڈا" کا مطلب ہے؟',['Cold','Hot','Warm','Cool'],'Cold','easy'],
['اردو میں "سخت" کا مطلب ہے؟',['Hard','Soft','Easy','Difficult'],'Hard','easy'],
['اردو میں "نرم" کا مطلب ہے؟',['Soft','Hard','Easy','Difficult'],'Soft','easy'],
['اردو میں "آسان" کا مطلب ہے؟',['Easy','Difficult','Hard','Soft'],'Easy','easy'],
['اردو میں "مشکل" کا مطلب ہے؟',['Difficult','Easy','Hard','Soft'],'Difficult','easy'],
['اردو میں "صاف" کا مطلب ہے؟',['Clean','Dirty','Pure','Clear'],'Clean','easy'],
['اردو میں "گندا" کا مطلب ہے؟',['Dirty','Clean','Pure','Clear'],'Dirty','easy'],
['اردو میں "روشن" کا مطلب ہے؟',['Bright','Dark','Light','Dim'],'Bright','easy'],
['اردو میں "اندھیرا" کا مطلب ہے؟',['Dark','Bright','Light','Dim'],'Dark','easy'],
['اردو میں "چمکدار" کا مطلب ہے؟',['Shiny','Dull','Bright','Dark'],'Shiny','easy'],
['اردو میں "پھیکا" کا مطلب ہے؟',['Dull','Shiny','Bright','Dark'],'Dull','easy'],
['اردو میں "میٹھا" کا مطلب ہے؟',['Sweet','Sour','Bitter','Salty'],'Sweet','easy'],
['اردو میں "ترش" کا مطلب ہے؟',['Sour','Sweet','Bitter','Salty'],'Sour','easy'],
['اردو میں "کڑوا" کا مطلب ہے؟',['Bitter','Sweet','Sour','Salty'],'Bitter','easy'],
['اردو میں "نمکین" کا مطلب ہے؟',['Salty','Sweet','Sour','Bitter'],'Salty','easy'],
['اردو میں "تکلیف" کا مطلب ہے؟',['Pain','Joy','Happiness','Comfort'],'Pain','easy'],
['اردو میں "خوشی" کا مطلب ہے؟',['Happiness','Pain','Sadness','Anger'],'Happiness','easy'],
['اردو میں "غم" کا مطلب ہے؟',['Sadness','Happiness','Pain','Anger'],'Sadness','easy'],
['اردو میں "غصہ" کا مطلب ہے؟',['Anger','Happiness','Sadness','Pain'],'Anger','easy'],
['اردو میں "ڈر" کا مطلب ہے؟',['Fear','Courage','Bravery','Strength'],'Fear','easy'],
['اردو میں "ہمت" کا مطلب ہے؟',['Courage','Fear','Cowardice','Weakness'],'Courage','easy'],
['اردو میں "دوست" کا مطلب ہے؟',['Friend','Enemy','Stranger','Relative'],'Friend','easy'],
['اردو میں "دشمن" کا مطلب ہے؟',['Enemy','Friend','Stranger','Relative'],'Enemy','easy'],
['اردو میں "پیار" کا مطلب ہے؟',['Love','Hate','Anger','Sadness'],'Love','easy'],
['اردو میں "نفرت" کا مطلب ہے؟',['Hate','Love','Anger','Sadness'],'Hate','easy'],
['اردو میں "دوا" کا مطلب ہے؟',['Medicine','Disease','Doctor','Hospital'],'Medicine','easy'],
['اردو میں "بیماری" کا مطلب ہے؟',['Disease','Medicine','Doctor','Hospital'],'Disease','easy'],
['اردو میں "ڈاکٹر" کا مطلب ہے؟',['Doctor','Patient','Nurse','Hospital'],'Doctor','easy'],
['اردو میں "مریض" کا مطلب ہے؟',['Patient','Doctor','Nurse','Hospital'],'Patient','easy'],
['اردو میں "اسکول" کا مطلب ہے؟',['School','College','University','Hospital'],'School','easy'],
['اردو میں "استاد" کا مطلب ہے؟',['Teacher','Student','Principal','Doctor'],'Teacher','easy'],
['اردو میں "طالب علم" کا مطلب ہے؟',['Student','Teacher','Principal','Doctor'],'Student','easy'],
['اردو میں "کمرہ" کا مطلب ہے؟',['Room','House','Building','Door'],'Room','easy'],
['اردو میں "گھر" کا مطلب ہے؟',['House','Room','Building','Door'],'House','easy'],
['اردو میں "دروازہ" کا مطلب ہے؟',['Door','Window','Wall','Roof'],'Door','easy'],
['اردو میں "کھڑکی" کا مطلب ہے؟',['Window','Door','Wall','Roof'],'Window','easy'],
['اردو میں "دیوار" کا مطلب ہے؟',['Wall','Door','Window','Roof'],'Wall','easy'],
['اردو میں "چھت" کا مطلب ہے؟',['Roof','Wall','Door','Window'],'Roof','easy'],
['اردو میں "کرسی" کا مطلب ہے؟',['Chair','Table','Bed','Sofa'],'Chair','easy'],
['اردو میں "میز" کا مطلب ہے؟',['Table','Chair','Bed','Sofa'],'Table','easy'],
['اردو میں "بستر" کا مطلب ہے؟',['Bed','Chair','Table','Sofa'],'Bed','easy'],
['اردو میں "سوفا" کا مطلب ہے؟',['Sofa','Chair','Table','Bed'],'Sofa','easy'],
['اردو میں "پنکھا" کا مطلب ہے؟',['Fan','Light','AC','Heater'],'Fan','easy'],
['اردو میں "بلب" کا مطلب ہے؟',['Bulb','Fan','Light','AC'],'Bulb','easy'],
['اردو میں "پانی" کا مطلب ہے؟',['Water','Milk','Juice','Tea'],'Water','easy'],
['اردو میں "دودھ" کا مطلب ہے؟',['Milk','Water','Juice','Tea'],'Milk','easy'],
['اردو میں "رس" کا مطلب ہے؟',['Juice','Milk','Water','Tea'],'Juice','easy'],
['اردو میں "چائے" کا مطلب ہے؟',['Tea','Coffee','Juice','Milk'],'Tea','easy'],
['اردو میں "قہوہ" کا مطلب ہے؟',['Coffee','Tea','Juice','Milk'],'Coffee','easy'],
['اردو میں "روٹی" کا مطلب ہے؟',['Bread','Rice','Meat','Vegetable'],'Bread','easy'],
['اردو میں "چاول" کا مطلب ہے؟',['Rice','Bread','Meat','Vegetable'],'Rice','easy'],
['اردو میں "گوشت" کا مطلب ہے؟',['Meat','Bread','Rice','Vegetable'],'Meat','easy'],
['اردو میں "سبزی" کا مطلب ہے؟',['Vegetable','Meat','Bread','Rice'],'Vegetable','easy'],
['اردو میں "پھل" کا مطلب ہے؟',['Fruit','Vegetable','Meat','Bread'],'Fruit','easy'],
['اردو میں "سیب" کا مطلب ہے؟',['Apple','Banana','Mango','Orange'],'Apple','easy'],
['اردو میں "کیلا" کا مطلب ہے؟',['Banana','Apple','Mango','Orange'],'Banana','easy'],
['اردو میں "آم" کا مطلب ہے؟',['Mango','Apple','Banana','Orange'],'Mango','easy'],
['اردو میں "مالٹا" کا مطلب ہے؟',['Orange','Apple','Banana','Mango'],'Orange','easy'],
['اردو میں "انگور" کا مطلب ہے؟',['Grapes','Apple','Banana','Mango'],'Grapes','easy'],
['اردو میں "آلو" کا مطلب ہے؟',['Potato','Tomato','Onion','Carrot'],'Potato','easy'],
['اردو میں "ٹماٹر" کا مطلب ہے؟',['Tomato','Potato','Onion','Carrot'],'Tomato','easy'],
['اردو میں "پیاز" کا مطلب ہے؟',['Onion','Potato','Tomato','Carrot'],'Onion','easy'],
['اردو میں "گاجر" کا مطلب ہے؟',['Carrot','Potato','Tomato','Onion'],'Carrot','easy'],
['اردو میں "مرغی" کا مطلب ہے؟',['Chicken','Goat','Cow','Sheep'],'Chicken','easy'],
['اردو میں "بکری" کا مطلب ہے؟',['Goat','Chicken','Cow','Sheep'],'Goat','easy'],
['اردو میں "گائے" کا مطلب ہے؟',['Cow','Chicken','Goat','Sheep'],'Cow','easy'],
['اردو میں "بھیڑ" کا مطلب ہے؟',['Sheep','Chicken','Goat','Cow'],'Sheep','easy'],
['اردو میں "شیر" کا مطلب ہے؟',['Lion','Tiger','Elephant','Bear'],'Lion','easy'],
['اردو میں "چیتا" کا مطلب ہے؟',['Tiger','Lion','Elephant','Bear'],'Tiger','easy'],
['اردو میں "ہاتھی" کا مطلب ہے؟',['Elephant','Lion','Tiger','Bear'],'Elephant','easy'],
['اردو میں "بھالو" کا مطلب ہے؟',['Bear','Lion','Tiger','Elephant'],'Bear','easy'],
['اردو میں "خرگوش" کا مطلب ہے؟',['Rabbit','Cat','Dog','Mouse'],'Rabbit','easy'],
['اردو میں "بلی" کا مطلب ہے؟',['Cat','Dog','Rabbit','Mouse'],'Cat','easy'],
['اردو میں "کتا" کا مطلب ہے؟',['Dog','Cat','Rabbit','Mouse'],'Dog','easy'],
['اردو میں "چوہا" کا مطلب ہے؟',['Mouse','Cat','Dog','Rabbit'],'Mouse','easy'],
['اردو میں "کاgu" کا مطلب ہے؟',['Crow','Sparrow','Parrot','Eagle'],'Crow','easy'],
['اردو میں "چڑیا" کا مطلب ہے؟',['Sparrow','Crow','Parrot','Eagle'],'Sparrow','easy'],
['اردو میں "طوطا" کا مطلب ہے؟',['Parrot','Crow','Sparrow','Eagle'],'Parrot','easy'],
['اردو میں "عقاب" کا مطلب ہے؟',['Eagle','Crow','Sparrow','Parrot'],'Eagle','easy'],
['اردو میں "مچھلی" کا مطلب ہے؟',['Fish','Bird','Animal','Insect'],'Fish','easy'],
['اردو میں "مچھر" کا مطلب ہے؟',['Mosquito','Fly','Ant','Bee'],'Mosquito','easy'],
['اردو میں "مکھی" کا مطلب ہے؟',['Fly','Mosquito','Ant','Bee'],'Fly','easy'],
['اردو میں "چیونٹی" کا مطلب ہے؟',['Ant','Mosquito','Fly','Bee'],'Ant','easy'],
['اردو میں "مکھی" کا مطلب ہے؟',['Bee','Mosquito','Fly','Ant'],'Bee','easy'],
['اردو میں "تیتلی" کا مطلب ہے؟',['Butterfly','Bee','Ant','Fly'],'Butterfly','easy'],
['اردو میں "شہر" کا مطلب ہے؟',['City','Village','Town','Country'],'City','easy'],
['اردو میں "گاؤں" کا مطلب ہے؟',['Village','City','Town','Country'],'Village','easy'],
['اردو میں "دیہات" کا مطلب ہے؟',['Village','City','Town','Country'],'Village','easy'],
['اردو میں "ملک" کا مطلب ہے؟',['Country','City','Village','Town'],'Country','easy'],
['اردو میں "سڑک" کا مطلب ہے؟',['Road','Street','Highway','Bridge'],'Road','easy'],
['اردو میں "پل" کا مطلب ہے؟',['Bridge','Road','Street','Highway'],'Bridge','easy'],
['اردو میں "گاڑی" کا مطلب ہے؟',['Car','Bus','Truck','Bike'],'Car','easy'],
['اردو میں "بس" کا مطلب ہے؟',['Bus','Car','Truck','Bike'],'Bus','easy'],
['اردو میں "ٹرک" کا مطلب ہے؟',['Truck','Car','Bus','Bike'],'Truck','easy'],
['اردو میں "موٹرسائیکل" کا مطلب ہے؟',['Bike','Car','Bus','Truck'],'Bike','easy'],
['اردو میں "سائیکل" کا مطلب ہے؟',['Bicycle','Bike','Car','Bus'],'Bicycle','easy'],
['اردو میں "ہوائی جہاز" کا مطلب ہے؟',['Aeroplane','Helicopter','Rocket','Jet'],'Aeroplane','easy'],
['اردو میں "کشتی" کا مطلب ہے؟',['Boat','Ship','Aeroplane','Submarine'],'Boat','easy'],
['اردو میں "جہاز" کا مطلب ہے؟',['Ship','Boat','Aeroplane','Submarine'],'Ship','easy'],
['اردو میں "ریلوے" کا مطلب ہے؟',['Train','Bus','Car','Aeroplane'],'Train','easy'],
['اردو میں "اسپتال" کا مطلب ہے؟',['Hospital','School','College','Office'],'Hospital','easy'],
['اردو میں "دکان" کا مطلب ہے؟',['Shop','School','Hospital','Office'],'Shop','easy'],
['اردو میں "دفتر" کا مطلب ہے؟',['Office','Shop','School','Hospital'],'Office','easy'],
['اردو میں "بازار" کا مطلب ہے؟',['Market','Shop','Office','School'],'Market','easy'],
['اردو میں "مسجد" کا مطلب ہے؟',['Mosque','Church','Temple','Gurdwara'],'Mosque','easy'],
['اردو میں "گرجا" کا مطلب ہے؟',['Church','Mosque','Temple','Gurdwara'],'Church','easy'],
['اردو میں "مندر" کا مطلب ہے؟',['Temple','Mosque','Church','Gurdwara'],'Temple','easy'],
['اردو میں "درگاہ" کا مطلب ہے؟',['Shrine','Mosque','Church','Temple'],'Shrine','easy'],
['اردو میں "قبرستان" کا مطلب ہے؟',['Graveyard','Garden','Park','Ground'],'Graveyard','easy'],
['اردو میں "باغ" کا مطلب ہے؟',['Garden','Park','Graveyard','Ground'],'Garden','easy'],
['اردو میں "پارک" کا مطلب ہے؟',['Park','Garden','Ground','Graveyard'],'Park','easy'],
['اردو میں "میدان" کا مطلب ہے؟',['Ground','Park','Garden','Graveyard'],'Ground','easy'],
['اردو میں "کھیتی" کا مطلب ہے؟',['Farming','Gardening','Cooking','Building'],'Farming','easy'],
['اردو میں "کسان" کا مطلب ہے؟',['Farmer','Teacher','Doctor','Worker'],'Farmer','easy'],
['اردو میں "مزدور" کا مطلب ہے؟',['Worker','Farmer','Teacher','Doctor'],'Worker','easy'],
['اردو میں "فوجی" کا مطلب ہے؟',['Soldier','Police','Doctor','Teacher'],'Soldier','easy'],
['اردو میں "پولیس" کا مطلب ہے؟',['Police','Soldier','Army','Guard'],'Police','easy'],
['اردو میں "چوکیدار" کا مطلب ہے؟',['Guard','Police','Soldier','Watchman'],'Guard','easy'],
['اردو میں "وقت" کا مطلب ہے؟',['Time','Clock','Watch','Hour'],'Time','easy'],
['اردو میں "گھڑی" کا مطلب ہے؟',['Clock','Time','Watch','Hour'],'Clock','easy'],
['اردو میں "دن" کا مطلب ہے؟',['Day','Night','Morning','Evening'],'Day','easy'],
['اردو میں "رات" کا مطلب ہے؟',['Night','Day','Morning','Evening'],'Night','easy'],
['اردو میں "صبح" کا مطلب ہے؟',['Morning','Evening','Night','Day'],'Morning','easy'],
['اردو میں "شام" کا مطلب ہے؟',['Evening','Morning','Night','Day'],'Evening','easy'],
['اردو میں "گھنٹہ" کا مطلب ہے؟',['Hour','Minute','Second','Day'],'Hour','easy'],
['اردو میں "منٹ" کا مطلب ہے؟',['Minute','Hour','Second','Day'],'Minute','easy'],
['اردو میں "سیکنڈ" کا مطلب ہے؟',['Second','Minute','Hour','Day'],'Second','easy'],
['اردو میں "ہفتہ" کا مطلب ہے؟',['Week','Month','Year','Day'],'Week','easy'],
['اردو میں "مہینہ" کا مطلب ہے؟',['Month','Week','Year','Day'],'Month','easy'],
['اردو میں "سال" کا مطلب ہے؟',['Year','Month','Week','Day'],'Year','easy'],
['اردو میں "کل" کا مطلب ہے؟',['Yesterday','Tomorrow','Today','Now'],'Yesterday','easy'],
['اردو میں "آج" کا مطلب ہے؟',['Today','Tomorrow','Yesterday','Now'],'Today','easy'],
['اردو میں "کل" (future) کا مطلب ہے؟',['Tomorrow','Today','Yesterday','Now'],'Tomorrow','easy'],
['اردو میں "اب" کا مطلب ہے؟',['Now','Then','Before','After'],'Now','easy'],
['اردو میں "پہلے" کا مطلب ہے؟',['Before','After','Now','Then'],'Before','easy'],
['اردو میں "بعد" کا مطلب ہے؟',['After','Before','Now','Then'],'After','easy'],
['اردو میں "دائیں" کا مطلب ہے؟',['Right','Left','Up','Down'],'Right','easy'],
['اردو میں "بائیں" کا مطلب ہے؟',['Left','Right','Up','Down'],'Left','easy'],
['اردو میں "اوپر" کا مطلب ہے؟',['Up','Down','Right','Left'],'Up','easy'],
['اردو میں "نیچے" کا مطلب ہے؟',['Down','Up','Right','Left'],'Down','easy'],
['اردو میں "آگے" کا مطلب ہے؟',['Front','Back','Right','Left'],'Front','easy'],
['اردو میں "پیچھے" کا مطلب ہے؟',['Back','Front','Right','Left'],'Back','easy'],
['اردو میں "قریب" کا مطلب ہے؟',['Near','Far','Close','Distant'],'Near','easy'],
['اردو میں "دور" کا مطلب ہے؟',['Far','Near','Close','Distant'],'Far','easy'],
['اردو میں "پورا" کا مطلب ہے؟',['Complete','Incomplete','Half','Partial'],'Complete','easy'],
['اردو میں "ادھورا" کا مطلب ہے؟',['Incomplete','Complete','Half','Partial'],'Incomplete','easy'],
['اردو میں "کامیاب" کا مطلب ہے؟',['Successful','Failure','Unsuccessful','Defeat'],'Successful','easy'],
['اردو میں "ناکام" کا مطلب ہے؟',['Unsuccessful','Successful','Failure','Defeat'],'Unsuccessful','easy'],
['اردو میں "کام" کا مطلب ہے؟',['Work','Play','Rest','Sleep'],'Work','easy'],
['اردو میں "کھیل" کا مطلب ہے؟',['Game','Work','Study','Sleep'],'Game','easy'],
['اردو میں "پڑھائی" کا مطلب ہے؟',['Study','Play','Work','Sleep'],'Study','easy'],
['اردو میں "سونا" کا مطلب ہے؟',['Sleep','Study','Play','Work'],'Sleep','easy'],
['اردو میں "جاگنا" کا مطلب ہے؟',['Wake','Sleep','Study','Play'],'Wake','easy'],
['اردو میں "کھانا" کا مطلب ہے؟',['Eat','Drink','Sleep','Play'],'Eat','easy'],
['اردو میں "پینا" کا مطلب ہے؟',['Drink','Eat','Sleep','Play'],'Drink','easy'],
['اردو میں "دوڑنا" کا مطلب ہے؟',['Run','Walk','Jump','Swim'],'Run','easy'],
['اردو میں "چلنا" کا مطلب ہے؟',['Walk','Run','Jump','Swim'],'Walk','easy'],
['اردو میں "کودنا" کا مطلب ہے؟',['Jump','Run','Walk','Swim'],'Jump','easy'],
['اردو میں "تیرنا" کا مطلب ہے؟',['Swim','Run','Walk','Jump'],'Swim','easy'],
['اردو میں "پڑھنا" کا مطلب ہے؟',['Read','Write','Speak','Listen'],'Read','easy'],
['اردو میں "لکھنا" کا مطلب ہے؟',['Write','Read','Speak','Listen'],'Write','easy'],
['اردو میں "بولنا" کا مطلب ہے؟',['Speak','Read','Write','Listen'],'Speak','easy'],
['اردو میں "سننا" کا مطلب ہے؟',['Listen','Read','Write','Speak'],'Listen','easy'],
['اردو میں "دیکھنا" کا مطلب ہے؟',['See','Hear','Touch','Smell'],'See','easy'],
['اردو میں "سونگھنا" کا مطلب ہے؟',['Smell','See','Hear','Touch'],'Smell','easy'],
['اردو میں "چکھنا" کا مطلب ہے؟',['Taste','Smell','See','Hear'],'Taste','easy'],
['اردو میں "چھونا" کا مطلب ہے؟',['Touch','See','Hear','Smell'],'Touch','easy'],
['اردو میں "قومی ترانہ پاکستان کس نے لکھا؟',['حفیظ جالندھری','اقبال','فیض','غالب'],'حفیض جالندھری','easy'],
['اردو میں "تیرے بعد" کس کا شعری مجموعہ ہے؟',['پروین شاکر','فہمیدہ ریاض','ادثر حسین','فیض احمد فیض'],'پروین شاکر','hard'],
['اردو زبان کی پہلی نظم کس نے لکھی؟',['علی گڑھ کے طلباء','امیر خسرو','غالب','اقبال'],'علی گڑھ کے طلباء','hard'],
['اردو کا پہلا ناول کون سا ہے؟',['مراۃ العروس','عورت','بہن','نئی دنیا'],'مراۃ العروس','hard'],
['مرزا ہادی رسوا کا مشہور ناول؟',['امراٰو جان ada','عورت','بہن','نئی دنیا'],'امراٰو جان ada','medium'],
['اردو میں "بہادر" کا مطلب ہے؟',['Brave','Coward','Strong','Weak'],'Brave','easy'],
['اردو میں "بزدل" کا مطلب ہے؟',['Coward','Brave','Strong','Weak'],'Coward','easy'],
['اردو میں "سچ" کا مطلب ہے؟',['Truth','Lie','Story','News'],'Truth','easy'],
['اردو میں "جھوٹ" کا مطلب ہے؟',['Lie','Truth','Story','News'],'Lie','easy'],
['اردو میں "خبر" کا مطلب ہے؟',['News','Story','Truth','Lie'],'News','easy'],
['اردو میں "کہانی" کا مطلب ہے؟',['Story','News','Truth','Lie'],'Story','easy'],
['اردو میں "شعر" کا مطلب ہے؟',['Poetry','Story','News','Novel'],'Poetry','easy'],
['اردو میں "نظم" کا مطلب ہے؟',['Poem','Story','News','Novel'],'Poem','easy'],
['اردو میں "ناول" کا مطلب ہے؟',['Novel','Poem','Story','News'],'Novel','easy'],
['اردو میں "افسانہ" کا مطلب ہے؟',['Short Story','Novel','Poem','News'],'Short Story','easy'],
['اردو میں "مضمون" کا مطلب ہے؟',['Essay','Story','Poem','Novel'],'Essay','easy'],
['اردو میں "انشا" کا مطلب ہے؟',['Composition','Essay','Story','Poem'],'Composition','easy'],
['اردو میں "خط" کا مطلب ہے؟',['Letter','Book','Page','Note'],'Letter','easy'],
['اردو میں "تختہ" کا مطلب ہے؟',['Blackboard','Book','Page','Desk'],'Blackboard','easy'],
['اردو میں "چاک" کا مطلب ہے؟',['Chalk','Book','Pen','Pencil'],'Chalk','easy'],
['اردو میں "قلم" کا مطلب ہے؟',['Pen','Pencil','Chalk','Book'],'Pen','easy'],
['اردو میں "پنسل" کا مطلب ہے؟',['Pencil','Pen','Chalk','Book'],'Pencil','easy'],
['اردو میں "کاغذ" کا مطلب ہے؟',['Paper','Book','Page','Card'],'Paper','easy'],
['اردو میں "کتاب" کا مطلب ہے؟',['Book','Paper','Page','Note'],'Book','easy'],
['اردو میں "جزو" کا مطلب ہے؟',['Notebook','Book','Paper','Page'],'Notebook','easy'],
['اردو میں "بیگ" کا مطلب ہے؟',['Bag','Box','Case','Packet'],'Bag','easy'],
['اردو میں "بوتل" کا مطلب ہے؟',['Bottle','Glass','Cup','Jug'],'Bottle','easy'],
['اردو میں "گلاس" کا مطلب ہے؟',['Glass','Bottle','Cup','Jug'],'Glass','easy'],
['اردو میں "کپ" کا مطلب ہے؟',['Cup','Glass','Bottle','Jug'],'Cup','easy'],
['اردو میں "جگ" کا مطلب ہے؟',['Jug','Cup','Glass','Bottle'],'Jug','easy'],
['اردو میں "چمچ" کا مطلب ہے؟',['Spoon','Fork','Knife','Plate'],'Spoon','easy'],
['اردو میں "کانٹا" کا مطلب ہے؟',['Fork','Spoon','Knife','Plate'],'Fork','easy'],
['اردو میں "چاقو" کا مطلب ہے؟',['Knife','Fork','Spoon','Plate'],'Knife','easy'],
['اردو میں "پلیٹ" کا مطلب ہے؟',['Plate','Bowl','Cup','Glass'],'Plate','easy'],
['اردو میں "کٹورا" کا مطلب ہے؟',['Bowl','Plate','Cup','Glass'],'Bowl','easy'],
['اردو میں "نوالہ" کا مطلب ہے؟',['Morsel','Plate','Bowl','Cup'],'Morsel','medium'],
['اردو میں "دعوت" کا مطلب ہے؟',['Invitation','Food','Party','Gift'],'Invitation','medium'],
['اردو میں "تہوار" کا مطلب ہے؟',['Festival','Party','Invitation','Day'],'Festival','medium'],
['اردو میں "جشن" کا مطلب ہے؟',['Celebration','Festival','Party','Day'],'Celebration','medium'],
['اردو میں "عید" کا مطلب ہے؟',['Eid','Festival','Celebration','Day'],'Eid','easy'],
['اردو میں "عید الفطر" کس کے بعد آتی ہے؟',['Ramadan','Shawwal','Muharram','Dhul Hijjah'],'Ramadan','medium'],
['اردو میں "عید الاضحی" کس کے بعد آتی ہے؟',['Hajj','Ramadan','Shawwal','Muharram'],'Hajj','medium'],
['اردو میں "شب برات" کس مہینے میں آتی ہے؟',['Shaban','Ramadan','Shawwal','Rajab'],'Shaban','medium'],
['اردو میں "لیلۃ القدر" کس مہینے میں ہے؟',['Ramadan','Shawwal','Shaban','Muharram'],'Ramadan','medium'],
['اردو میں "جمعہ" کا مطلب ہے؟',['Friday','Saturday','Sunday','Monday'],'Friday','easy'],
['اردو میں "ہفتہ" کا مطلب ہے؟',['Saturday','Friday','Sunday','Monday'],'Saturday','easy'],
['اردو میں "اتوار" کا مطلب ہے؟',['Sunday','Saturday','Friday','Monday'],'Sunday','easy'],
['اردو میں "پیر" کا مطلب ہے؟',['Monday','Sunday','Tuesday','Wednesday'],'Monday','easy'],
['اردو میں "منگل" کا مطلب ہے؟',['Tuesday','Monday','Wednesday','Thursday'],'Tuesday','easy'],
['اردو میں "بدھ" کا مطلب ہے؟',['Wednesday','Tuesday','Thursday','Friday'],'Wednesday','easy'],
['اردو میں "جمعرات" کا مطلب ہے؟',['Thursday','Wednesday','Friday','Saturday'],'Thursday','easy'],
['اردو میں "جانور" کا مطلب ہے؟',['Animal','Bird','Fish','Insect'],'Animal','easy'],
['اردو میں "پرندہ" کا مطلب ہے؟',['Bird','Animal','Fish','Insect'],'Bird','easy'],
['اردو میں "کیڑا" کا مطلب ہے؟',['Insect','Animal','Bird','Fish'],'Insect','easy'],
['اردو میں "مکان" کا مطلب ہے؟',['House','Room','Building','Shop'],'House','easy'],
['اردو میں "عمارت" کا مطلب ہے؟',['Building','House','Room','Shop'],'Building','easy'],
['اردو میں "پل" کا مطلب ہے؟',['Bridge','Road','Building','Shop'],'Bridge','easy'],
['اردو میں "کنواں" کا مطلب ہے؟',['Well','Pond','River','Lake'],'Well','easy'],
['اردو میں "حوض" کا مطلب ہے؟',['Pond','Well','River','Lake'],'Pond','easy'],
['اردو میں "دریا" کا مطلب ہے؟',['River','Pond','Well','Lake'],'River','easy'],
['اردو میں "جھیل" کا مطلب ہے؟',['Lake','River','Pond','Well'],'Lake','easy'],
['اردو میں "سمندر" کا مطلب ہے؟',['Sea','River','Lake','Pond'],'Sea','easy'],
['اردو میں "بارش" کا مطلب ہے؟',['Rain','Snow','Wind','Storm'],'Rain','easy'],
['اردو میں "برف" کا مطلب ہے؟',['Snow','Rain','Wind','Storm'],'Snow','easy'],
['اردو میں "آندھی" کا مطلب ہے؟',['Storm','Wind','Rain','Snow'],'Storm','easy'],
['اردو میں "ہوا" کا مطلب ہے؟',['Wind','Storm','Rain','Snow'],'Wind','easy'],
['اردو میں "دھوپ" کا مطلب ہے؟',['Sunshine','Rain','Snow','Wind'],'Sunshine','easy'],
['اردو میں "چھاؤں" کا مطلب ہے؟',['Shade','Sunshine','Rain','Snow'],'Shade','easy'],
['اردو میں "بادل" کا مطلب ہے؟',['Cloud','Rain','Snow','Wind'],'Cloud','easy'],
['اردو میں "آگ" کا مطلب ہے؟',['Fire','Water','Air','Earth'],'Fire','easy'],
['اردو میں "دھواں" کا مطلب ہے؟',['Smoke','Fire','Air','Cloud'],'Smoke','easy'],
['اردو میں "چراغ" کا مطلب ہے؟',['Lamp','Bulb','Candle','Light'],'Lamp','easy'],
['اردو میں "موم بتی" کا مطلب ہے؟',['Candle','Lamp','Bulb','Light'],'Candle','easy'],
['اردو میں "دھات" کا مطلب ہے؟',['Metal','Wood','Stone','Glass'],'Metal','easy'],
['اردو میں "لکڑی" کا مطلب ہے؟',['Wood','Metal','Stone','Glass'],'Wood','easy'],
['اردو میں "پتھر" کا مطلب ہے؟',['Stone','Metal','Wood','Glass'],'Stone','easy'],
['اردو میں "کانچ" کا مطلب ہے؟',['Glass','Metal','Wood','Stone'],'Glass','easy'],
['اردو میں "کپڑا" کا مطلب ہے؟',['Cloth','Paper','Wood','Metal'],'Cloth','easy'],
['اردو میں "تار" کا مطلب ہے؟',['Thread','Cloth','Paper','Wire'],'Thread','easy'],
['اردو میں "تار" (electric) کا مطلب ہے؟',['Wire','Thread','Cloth','Pipe'],'Wire','easy'],
['اردو میں "نل" کا مطلب ہے؟',['Tap','Pipe','Wire','Thread'],'Tap','easy'],
['اردو میں "پائپ" کا مطلب ہے؟',['Pipe','Tap','Wire','Thread'],'Pipe','easy'],
['اردو میں "تالا" کا مطلب ہے؟',['Lock','Key','Door','Gate'],'Lock','easy'],
['اردو میں "چابی" کا مطلب ہے؟',['Key','Lock','Door','Gate'],'Key','easy'],
['اردو میں "دریچہ" کا مطلب ہے؟',['Window','Door','Gate','Wall'],'Window','easy'],
['اردو میں "دیوار" کا مطلب ہے؟',['Wall','Window','Door','Gate'],'Wall','easy'],
['اردو میں "چھجا" کا مطلب ہے؟',['Roof','Wall','Window','Door'],'Roof','medium'],
['اردو میں "سیڑھی" کا مطلب ہے؟',['Stairs','Ladder','Wall','Door'],'Stairs','easy'],
['اردو میں "نرد" کا مطلب ہے؟',['Ladder','Stairs','Wall','Door'],'Ladder','easy'],
['اردو میں "بستر" کا مطلب ہے؟',['Bed','Sofa','Chair','Table'],'Bed','easy'],
['اردو میں "تکیہ" کا مطلب ہے؟',['Pillow','Bed','Sofa','Chair'],'Pillow','easy'],
['اردو میں "کمبل" کا مطلب ہے؟',['Blanket','Pillow','Bed','Sheet'],'Blanket','easy'],
['اردو میں "چادر" کا مطلب ہے؟',['Sheet','Blanket','Pillow','Bed'],'Sheet','easy'],
['اردو میں "الماری" کا مطلب ہے؟',['Cupboard','Table','Chair','Bed'],'Cupboard','easy'],
['اردو میں "دراز" کا مطلب ہے؟',['Drawer','Cupboard','Table','Chair'],'Drawer','easy'],
['اردو میں "آئینہ" کا مطلب ہے؟',['Mirror','Glass','Window','Door'],'Mirror','easy'],
['اردو میں "صابن" کا مطلب ہے؟',['Soap','Oil','Cream','Powder'],'Soap','easy'],
['اردو میں "تیل" کا مطلب ہے؟',['Oil','Soap','Cream','Powder'],'Oil','easy'],
['اردو میں "پاؤڈر" کا مطلب ہے؟',['Powder','Soap','Oil','Cream'],'Powder','easy'],
['اردو میں "کریم" کا مطلب ہے؟',['Cream','Powder','Soap','Oil'],'Cream','easy'],
['اردو میں "برش" کا مطلب ہے؟',['Brush','Comb','Soap','Oil'],'Brush','easy'],
['اردو میں "کنگھی" کا مطلب ہے؟',['Comb','Brush','Soap','Oil'],'Comb','easy'],
['اردو میں "شیشہ" کا مطلب ہے؟',['Mirror','Glass','Window','Bottle'],'Mirror','easy'],
['اردو میں "بوتل" کا مطلب ہے؟',['Bottle','Glass','Jar','Box'],'Bottle','easy'],
['اردو میں "ڈبہ" کا مطلب ہے؟',['Box','Bottle','Jar','Bag'],'Box','easy'],
['اردو میں "جار" کا مطلب ہے؟',['Jar','Bottle','Box','Bag'],'Jar','easy'],
['اردو میں "ٹوکری" کا مطلب ہے؟',['Basket','Box','Bag','Jar'],'Basket','easy'],
['اردو میں "تھیلی" کا مطلب ہے؟',['Bag','Basket','Box','Jar'],'Bag','easy'],
['اردو میں "ریشمی" کا مطلب ہے؟',['Silky','Rough','Smooth','Soft'],'Silky','medium'],
['اردو میں "خوشبو" کا مطلب ہے؟',['Fragrance','Smell','Odour','Perfume'],'Fragrance','easy'],
['اردو میں "عطر" کا مطلب ہے؟',['Perfume','Fragrance','Smell','Odour'],'Perfume','easy'],
['اردو میں "گلاب" کا مطلب ہے؟',['Rose','Jasmine','Lily','Sunflower'],'Rose','easy'],
['اردو میں "چنبیلی" کا مطلب ہے؟',['Jasmine','Rose','Lily','Sunflower'],'Jasmine','easy'],
['اردو میں "سورج" کا مطلب ہے؟',['Sun','Moon','Star','Sky'],'Sun','easy'],
['اردو میں "چاند" کا مطلب ہے؟',['Moon','Sun','Star','Sky'],'Moon','easy'],
['اردو میں "تارا" کا مطلب ہے؟',['Star','Moon','Sun','Sky'],'Star','easy'],
['اردو میں "آسمان" کا مطلب ہے؟',['Sky','Sun','Moon','Star'],'Sky','easy'],
['اردو میں "زمین" کا مطلب ہے؟',['Earth','Sky','Sun','Moon'],'Earth','easy'],
['اردو میں "ہوا" کا مطلب ہے؟',['Air','Water','Fire','Earth'],'Air','easy'],
['اردو میں "آگ" کا مطلب ہے؟',['Fire','Water','Air','Earth'],'Fire','easy'],
['اردو میں "پانی" کا مطلب ہے؟',['Water','Fire','Air','Earth'],'Water','easy']];
urdu.forEach(x=>quizData.urdu.push(q(x[0],s(x[1]),x[2],x[3],x[4]||'',s(x[5]||[]))));
